### ISSUE TITLE
Mentioning default webserver IP address / URL to OTA images in README

### ISSUE THREAD

**Issue by mirko** [khcnz/Espressif2Arduino#2]
The README currently doesn't state from where Espressif2Arduino fetches further OTA (e.g. Tasmota) images.
Although it's obviously part of the sketch (`URL_ROM_2` and `URL_ROM_3`) it might make sense to state that in the README as well (?)

**Comment by khcnz** [comment]
Agree - will update

**Comment by khcnz** [comment]
Minor updates added
