### ISSUE TITLE
Hosting of prebuilt images

### ISSUE THREAD

**Issue by cputoaster** [khcnz/Espressif2Arduino#4]
At least for me it would be nicer to have some prebuilt images publicly available that address a static address (eg 10.10.7.123). So I could just download these + tasmota into the sonota static folder, connect to the ITEAD-xxx wifi, change the dhcp assigned address of my computer to .123 manually and run the sonota script with my wifi credentials. No compiling needed. Maybe hosted at the same place as the tasmota images? Would need 2 images per tasmota image I guess. Or could the first one always be the same?

**Comment by khcnz** [comment]
Agree. I want to create an all in one hosted solution that includes these images and the sonata code as well. Will see if I can get this done this weekend.

**Comment by khcnz** [comment]
EC2 instance with sonota/espressif2arduino prebuilt and preconfigured on it's way.. @mirko FYI

**Comment by cputoaster** [comment]
EC2? Interesting, now I am getting curious :-)

**Comment by khcnz** [comment]
Working nicely now - a few finishing touches to do but this will make unlocking the sonoffs super easy.

**Comment by khcnz** [comment]
I thought about this some more - don't think it makes sense to provide preconfigured binaries in the repo, too many variables (flash size, flash mode esp8266/esp8285 and of course ip ranges).

However, most people shouldn't need to build after i release the below - will setup another repo which pulls together sonota/espressif2arduino/tasmota.

If you want you can now try this out now - using sonota if you provision your device to use 

**servername**: sunlocker.khc.net.nz 
**port**: 443

ESP8266 1megabyte devices will autoupgrade to a fully working tasmota by themselves.

Will close this ticket to be replaced with new repo in next few days.
